plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

title: Grays Harbor Festival of Colors
description: The Grays Harbor Festival of Colors is the premier kite festival on the west coast, and takes place the first full weekend of june every year
url: https://www.graysharborfestivalofcolors.com/
author: Kyle Beveridge
social:
  name: Grays Harbor Festival of Colors
  links:
    - https://www.facebook.com/OceanShoresFesitvalOfColors/
